id: I34AC5F90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:13:11+00:00'
last_modified: '2022-06-08T08:19:17.477352+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22349
  title: བཟང་སྤྱོད་ཀྱི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6D01:
      image_group_id: I1KG22369
      title: ''
      total_pages: 98
      order: 1
      base_file: 6D01.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
