id: P008262
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG22349
  title: བཟང་སྤྱོད་ཀྱི་འགྲེལ་པ།
  author: ''
  volumes:
    4acb18d86f954ccfbeea8fa2f910f156:
      image_group_id: I1KG22369
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
